//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coding.Stock.Web.Cd_ProAtts {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblId;
		protected global::System.Web.UI.WebControls.TextBox txtProTypeID;
		protected global::System.Web.UI.WebControls.TextBox txtA100_1;
		protected global::System.Web.UI.WebControls.TextBox txtA100_2;
		protected global::System.Web.UI.WebControls.TextBox txtA100_3;
		protected global::System.Web.UI.WebControls.TextBox txtA100_4;
		protected global::System.Web.UI.WebControls.TextBox txtA100_5;
		protected global::System.Web.UI.WebControls.TextBox txtA100_6;
		protected global::System.Web.UI.WebControls.TextBox txtA100_7;
		protected global::System.Web.UI.WebControls.TextBox txtA100_8;
		protected global::System.Web.UI.WebControls.TextBox txtA100_9;
		protected global::System.Web.UI.WebControls.TextBox txtA100_10;
		protected global::System.Web.UI.WebControls.TextBox txtA100_11;
		protected global::System.Web.UI.WebControls.TextBox txtA100_12;
		protected global::System.Web.UI.WebControls.TextBox txtA100_13;
		protected global::System.Web.UI.WebControls.TextBox txtA100_14;
		protected global::System.Web.UI.WebControls.TextBox txtA100_15;
		protected global::System.Web.UI.WebControls.TextBox txtA100_16;
		protected global::System.Web.UI.WebControls.TextBox txtA100_17;
		protected global::System.Web.UI.WebControls.TextBox txtA100_18;
		protected global::System.Web.UI.WebControls.TextBox txtA100_19;
		protected global::System.Web.UI.WebControls.TextBox txtA100_20;
		protected global::System.Web.UI.WebControls.TextBox txtA100_21;
		protected global::System.Web.UI.WebControls.TextBox txtA100_22;
		protected global::System.Web.UI.WebControls.TextBox txtA100_23;
		protected global::System.Web.UI.WebControls.TextBox txtA100_24;
		protected global::System.Web.UI.WebControls.TextBox txtA100_25;
		protected global::System.Web.UI.WebControls.TextBox txtA100_26;
		protected global::System.Web.UI.WebControls.TextBox txtA100_27;
		protected global::System.Web.UI.WebControls.TextBox txtA100_28;
		protected global::System.Web.UI.WebControls.TextBox txtA100_29;
		protected global::System.Web.UI.WebControls.TextBox txtA100_30;
		protected global::System.Web.UI.WebControls.TextBox txtA100_31;
		protected global::System.Web.UI.WebControls.TextBox txtA100_32;
		protected global::System.Web.UI.WebControls.TextBox txtA100_33;
		protected global::System.Web.UI.WebControls.TextBox txtA100_34;
		protected global::System.Web.UI.WebControls.TextBox txtA100_35;
		protected global::System.Web.UI.WebControls.TextBox txtA100_36;
		protected global::System.Web.UI.WebControls.TextBox txtA100_37;
		protected global::System.Web.UI.WebControls.TextBox txtA100_38;
		protected global::System.Web.UI.WebControls.TextBox txtA100_39;
		protected global::System.Web.UI.WebControls.TextBox txtA100_40;
		protected global::System.Web.UI.WebControls.TextBox txtA100_41;
		protected global::System.Web.UI.WebControls.TextBox txtA100_42;
		protected global::System.Web.UI.WebControls.TextBox txtA100_43;
		protected global::System.Web.UI.WebControls.TextBox txtA100_44;
		protected global::System.Web.UI.WebControls.TextBox txtA100_45;
		protected global::System.Web.UI.WebControls.TextBox txtA100_46;
		protected global::System.Web.UI.WebControls.TextBox txtA100_47;
		protected global::System.Web.UI.WebControls.TextBox txtA100_48;
		protected global::System.Web.UI.WebControls.TextBox txtA100_49;
		protected global::System.Web.UI.WebControls.TextBox txtA100_50;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
