//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coding.Stock.Web.Cd_ProAtts {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblId;
	protected global::System.Web.UI.WebControls.Label lblProTypeID;
	protected global::System.Web.UI.WebControls.Label lblA100_1;
	protected global::System.Web.UI.WebControls.Label lblA100_2;
	protected global::System.Web.UI.WebControls.Label lblA100_3;
	protected global::System.Web.UI.WebControls.Label lblA100_4;
	protected global::System.Web.UI.WebControls.Label lblA100_5;
	protected global::System.Web.UI.WebControls.Label lblA100_6;
	protected global::System.Web.UI.WebControls.Label lblA100_7;
	protected global::System.Web.UI.WebControls.Label lblA100_8;
	protected global::System.Web.UI.WebControls.Label lblA100_9;
	protected global::System.Web.UI.WebControls.Label lblA100_10;
	protected global::System.Web.UI.WebControls.Label lblA100_11;
	protected global::System.Web.UI.WebControls.Label lblA100_12;
	protected global::System.Web.UI.WebControls.Label lblA100_13;
	protected global::System.Web.UI.WebControls.Label lblA100_14;
	protected global::System.Web.UI.WebControls.Label lblA100_15;
	protected global::System.Web.UI.WebControls.Label lblA100_16;
	protected global::System.Web.UI.WebControls.Label lblA100_17;
	protected global::System.Web.UI.WebControls.Label lblA100_18;
	protected global::System.Web.UI.WebControls.Label lblA100_19;
	protected global::System.Web.UI.WebControls.Label lblA100_20;
	protected global::System.Web.UI.WebControls.Label lblA100_21;
	protected global::System.Web.UI.WebControls.Label lblA100_22;
	protected global::System.Web.UI.WebControls.Label lblA100_23;
	protected global::System.Web.UI.WebControls.Label lblA100_24;
	protected global::System.Web.UI.WebControls.Label lblA100_25;
	protected global::System.Web.UI.WebControls.Label lblA100_26;
	protected global::System.Web.UI.WebControls.Label lblA100_27;
	protected global::System.Web.UI.WebControls.Label lblA100_28;
	protected global::System.Web.UI.WebControls.Label lblA100_29;
	protected global::System.Web.UI.WebControls.Label lblA100_30;
	protected global::System.Web.UI.WebControls.Label lblA100_31;
	protected global::System.Web.UI.WebControls.Label lblA100_32;
	protected global::System.Web.UI.WebControls.Label lblA100_33;
	protected global::System.Web.UI.WebControls.Label lblA100_34;
	protected global::System.Web.UI.WebControls.Label lblA100_35;
	protected global::System.Web.UI.WebControls.Label lblA100_36;
	protected global::System.Web.UI.WebControls.Label lblA100_37;
	protected global::System.Web.UI.WebControls.Label lblA100_38;
	protected global::System.Web.UI.WebControls.Label lblA100_39;
	protected global::System.Web.UI.WebControls.Label lblA100_40;
	protected global::System.Web.UI.WebControls.Label lblA100_41;
	protected global::System.Web.UI.WebControls.Label lblA100_42;
	protected global::System.Web.UI.WebControls.Label lblA100_43;
	protected global::System.Web.UI.WebControls.Label lblA100_44;
	protected global::System.Web.UI.WebControls.Label lblA100_45;
	protected global::System.Web.UI.WebControls.Label lblA100_46;
	protected global::System.Web.UI.WebControls.Label lblA100_47;
	protected global::System.Web.UI.WebControls.Label lblA100_48;
	protected global::System.Web.UI.WebControls.Label lblA100_49;
	protected global::System.Web.UI.WebControls.Label lblA100_50;


       
    }
}
